server:
  port: 8080

spring:
  application:
    name:
      api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users,/api/users/**

        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies,/api/movies/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings,/api/bookings/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments,/api/payments/**,/api/notifications,/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://${HOST_IP:localhost}:8761/eureka